### ISSUE TITLE
how to add jumpscares and doors

### ISSUE THREAD

**Issue by DynstinnProductions** [Oplexitie/Cupcakes-Framework#4]
im using this framework but i dont know how the code and all that works, also, i was using an old version of the template and it had something called advanced scrolling, it seems to be missing in the new verison. also, i wanted to add this feature where when the player puts there mouse to the very bottom of the screen, the camera flips over to show the area behind the player

**Comment by Oplexitie** [comment]
Please do not use the issue tracker to ask me how to make stuff. It's not made for that.
But regardless, I'll try to nudge you in the right direction.

As for not understanding the framework. I strongly advise you to look at the scripts, with Godot documentation on hand, and read the comments I wrote in the code to understand how it works. If you don't understand how the framework works to begin with, then you'll struggle to even finish making a game. You should also look into _class_name_, _extends_ and _signals_ since they're a big part of how the framework works.

If you still struggle adding the features you desire after that, then I advise you to look at [CF-Example-Project](https://github.com/Oplexitie/CF-Example-Project/tree/main). It's a partial remake of FNAC made using a very old version of this framework in Godot 3. While to code is kinda bad, there's still a few things to learn from it. Such as, how I made doors and jumpscares.

As for Advanced Scrolling. It was removed a couple months ago, because it conflicted with my vision of the project. It can still be added back in though with minimal effort.

I hope this helps. And good luck with your project.

**Comment by DynstinnProductions** [comment]
Oh, okay, tyy, I’m not really used to godot 2D much, and I thought that making a final fan game using ur framework which I think I found a few months ago would be nice, I had plenty of experience with 3D but 2D always confused me, I’ll check the scripts again and try, also, about the cf project, I did check it out but never really understood it, I’ll look at all these again and then see, also, where do I ask questions or give feedback?

**Comment by Oplexitie** [comment]
That's okay, I understand, the framework does have some parts that are not very well documented or a bit complicated to figure out. And I do not mind answering questions related to those. But when it comes to not understanding most of the framework or adding features, it puts me in a tough spot. 

You can ask questions on the Cupcakes Framework [GameJolt page](https://gamejolt.com/p/cupcakes-framework-a-fnaf-framework-for-godot-got-an-update-1-4-0-gz3aw9ns) or the Cupcakes Framework thread on the [Godot Café Discord server](https://discord.com/invite/zH7NUgz) (you can find the thread by looking up my username). I keep an eye on them every so often, and answer questions whenever I can.
